import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/core/molecules/navbar.molecule";
import Footer from "@/components/core/molecules/footer.molecule";
import { Toaster } from "@/components/ui/toaster";
import Cart from "./utils/cart/cart";
import ContextWrapper from "@/lib/context/context-wrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Hotel Omni",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ContextWrapper>
        <body className={poppins.className}>
          <Navbar />
          <main>{children}</main>
          <Cart />
          <Footer />
          <Toaster />
        </body>
      </ContextWrapper>
    </html>
  );
}
